import React from 'react';
import {
  FileDown,
  Printer,
  CheckCircle2,
  AlertTriangle,
  Award,
  BarChart3,
  Code2,
  ShieldCheck,
  TrendingUp,
  FileText
} from 'lucide-react';
import { AnalysisResponse } from '../types';
import { exportAnalysisPdf } from '../services/pdfExport';

interface ReportsViewProps {
  analysis: AnalysisResponse;
}

export function ReportsView({ analysis }: ReportsViewProps) {
  const p = analysis.parsedSections.personal;
  const ats = analysis.atsScore;
  const categories = Object.values(ats.categoryScores);

  const handlePrint = () => {
    window.print();
  };

  const handleExportPdf = () => {
    exportAnalysisPdf(analysis, p.name !== 'Not detected' ? p.name : 'Candidate');
  };

  return (
    <div className="space-y-6">
      {/* Top Action Bar */}
      <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl p-6 shadow-xl flex items-center justify-between flex-wrap gap-4 print:hidden">
        <div>
          <h2 className="text-xl font-bold text-slate-900 dark:text-white flex items-center gap-2">
            <FileDown className="w-5 h-5 text-indigo-600 dark:text-indigo-400" />
            <span>Comprehensive ATS Audit & Performance Report</span>
          </h2>
          <p className="text-xs text-slate-500 dark:text-slate-400 mt-1">
            Official academic evaluation report generated by ResumeAI's deterministic ML/NLP scoring engine.
          </p>
        </div>

        <div className="flex items-center gap-3">
          <button
            onClick={handlePrint}
            className="px-4 py-2 rounded-xl bg-white dark:bg-slate-800 hover:bg-slate-100 dark:hover:bg-slate-700 text-slate-700 dark:text-slate-300 border border-slate-300 dark:border-slate-700 font-semibold text-xs transition-colors flex items-center gap-1.5 shadow-2xs"
          >
            <Printer className="w-3.5 h-3.5" />
            <span>Print Report</span>
          </button>

          <button
            onClick={handleExportPdf}
            className="px-4 py-2 rounded-xl bg-indigo-600 hover:bg-indigo-700 text-white font-semibold text-xs transition-all shadow-md shadow-indigo-600/20 flex items-center gap-1.5"
          >
            <FileDown className="w-3.5 h-3.5" />
            <span>Download PDF</span>
          </button>
        </div>
      </div>

      {/* Printable Report Sheet */}
      <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl p-6 sm:p-10 shadow-xl space-y-8 print:border-none print:shadow-none print:p-0">
        {/* Report Header */}
        <div className="flex items-start justify-between pb-6 border-b border-slate-200 dark:border-slate-800 flex-wrap gap-4">
          <div>
            <div className="flex items-center gap-2 mb-1">
              <span className="text-[11px] font-mono font-bold uppercase tracking-wider text-indigo-600 dark:text-indigo-400">
                ResumeAI Academic & Enterprise Evaluation Report
              </span>
            </div>
            <h1 className="text-2xl sm:text-3xl font-black text-slate-900 dark:text-white tracking-tight">
              {p.name !== 'Not detected' ? p.name : 'Candidate Profile'}
            </h1>
            <p className="text-xs text-slate-500 dark:text-slate-400 mt-1">
              {p.email} • {p.phone} • {p.location}
            </p>
          </div>

          <div className="bg-slate-50 dark:bg-slate-950 p-4 rounded-2xl border border-slate-200 dark:border-slate-800 text-center shrink-0">
            <span className="text-[10px] font-bold text-slate-400 uppercase tracking-wider block mb-1">
              Overall ATS Score
            </span>
            <div className="text-4xl font-black text-indigo-600 dark:text-indigo-400 font-mono">
              {ats.overallScore}
              <span className="text-base font-normal text-slate-400">/100</span>
            </div>
            <span className={`text-[10px] px-2 py-0.5 rounded-full font-bold mt-2 inline-block ${
              ats.overallScore >= 80 ? 'bg-emerald-100 text-emerald-700' : ats.overallScore >= 60 ? 'bg-amber-100 text-amber-700' : 'bg-red-100 text-red-700'
            }`}>
              {ats.overallScore >= 80 ? 'Highly Competitive' : ats.overallScore >= 60 ? 'Needs Targeted Optimization' : 'High Rejection Risk'}
            </span>
          </div>
        </div>

        {/* 1. Score Breakdown Matrix */}
        <div className="space-y-4">
          <h3 className="text-sm font-bold text-slate-900 dark:text-white uppercase tracking-wider flex items-center gap-2 border-b border-slate-200 dark:border-slate-800 pb-2">
            <BarChart3 className="w-4 h-4 text-indigo-600" />
            <span>1. Deterministic 8-Factor ATS Score Breakdown</span>
          </h3>

          <div className="overflow-x-auto">
            <table className="w-full text-left text-xs border border-slate-200 dark:border-slate-800 rounded-xl overflow-hidden">
              <thead className="bg-slate-50 dark:bg-slate-950 text-slate-700 dark:text-slate-300 font-bold border-b border-slate-200 dark:border-slate-800">
                <tr>
                  <th className="py-2.5 px-4">Evaluation Factor</th>
                  <th className="py-2.5 px-4">Score / Max</th>
                  <th className="py-2.5 px-4">Performance</th>
                  <th className="py-2.5 px-4">Diagnostic Feedback</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-200 dark:divide-slate-800">
                {categories.map((cat) => (
                  <tr key={cat.category} className="hover:bg-slate-50/50 dark:hover:bg-slate-950/40">
                    <td className="py-2.5 px-4 font-semibold text-slate-900 dark:text-white">{cat.name}</td>
                    <td className="py-2.5 px-4 font-mono font-bold text-slate-700 dark:text-slate-300">
                      {cat.score} / {cat.maxScore}
                    </td>
                    <td className="py-2.5 px-4">
                      <div className="w-24 h-2 bg-slate-100 dark:bg-slate-800 rounded-full overflow-hidden">
                        <div
                          className={`h-full rounded-full ${
                            cat.percentage >= 80 ? 'bg-emerald-500' : cat.percentage >= 50 ? 'bg-amber-500' : 'bg-red-500'
                          }`}
                          style={{ width: `${cat.percentage}%` }}
                        />
                      </div>
                    </td>
                    <td className="py-2.5 px-4 text-slate-600 dark:text-slate-400">{cat.feedback}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>

        {/* 2. Skills Inventory */}
        <div className="space-y-3">
          <h3 className="text-sm font-bold text-slate-900 dark:text-white uppercase tracking-wider flex items-center gap-2 border-b border-slate-200 dark:border-slate-800 pb-2">
            <Code2 className="w-4 h-4 text-emerald-600" />
            <span>2. Canonical Skills Inventory ({analysis.skills.totalCount} Normalized Entities)</span>
          </h3>

          <div className="flex flex-wrap gap-1.5">
            {analysis.skills.matchedSkills.map((s) => (
              <span
                key={s.id}
                className="text-xs px-2.5 py-1 rounded-md bg-slate-50 dark:bg-slate-950 border border-slate-200 dark:border-slate-800 text-slate-700 dark:text-slate-300 font-medium"
              >
                {s.name}
              </span>
            ))}
          </div>
        </div>

        {/* 3. Strengths & Recommendations */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {/* Strengths */}
          <div className="space-y-3">
            <h3 className="text-xs font-bold text-slate-900 dark:text-white uppercase tracking-wider flex items-center gap-2 text-emerald-700 dark:text-emerald-400">
              <CheckCircle2 className="w-4 h-4" />
              <span>Verified Strengths</span>
            </h3>
            <div className="space-y-2 text-xs">
              {ats.strengths.map((str, i) => (
                <div key={i} className="flex items-start gap-2 bg-emerald-50/50 dark:bg-emerald-950/20 p-2.5 rounded-xl border border-emerald-100 dark:border-emerald-900/30 text-slate-700 dark:text-slate-300">
                  <span className="text-emerald-600 font-bold shrink-0">✓</span>
                  <span>{str}</span>
                </div>
              ))}
            </div>
          </div>

          {/* Actionable Recommendations */}
          <div className="space-y-3">
            <h3 className="text-xs font-bold text-slate-900 dark:text-white uppercase tracking-wider flex items-center gap-2 text-indigo-700 dark:text-indigo-400">
              <TrendingUp className="w-4 h-4" />
              <span>Actionable Next Steps</span>
            </h3>
            <div className="space-y-2 text-xs">
              {ats.recommendations.map((rec, i) => (
                <div key={i} className="flex items-start gap-2 bg-indigo-50/50 dark:bg-indigo-950/20 p-2.5 rounded-xl border border-indigo-100 dark:border-indigo-900/30 text-slate-700 dark:text-slate-300">
                  <span className="text-indigo-600 font-bold shrink-0">{i + 1}.</span>
                  <span>{rec}</span>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* 4. Target Job Match (if present) */}
        {analysis.jobMatch && (
          <div className="space-y-3">
            <h3 className="text-sm font-bold text-slate-900 dark:text-white uppercase tracking-wider flex items-center gap-2 border-b border-slate-200 dark:border-slate-800 pb-2">
              <Award className="w-4 h-4 text-purple-600" />
              <span>4. Target Job Match Analysis ({analysis.jobMatch.detectedJobRole})</span>
            </h3>

            <div className="p-4 bg-slate-50 dark:bg-slate-950 rounded-xl border border-slate-200 dark:border-slate-800 grid grid-cols-2 sm:grid-cols-4 gap-4 text-xs">
              <div>
                <span className="text-slate-500 block">Overall Fit:</span>
                <span className="font-bold text-indigo-600 text-lg">{analysis.jobMatch.overallMatchScore}%</span>
              </div>
              <div>
                <span className="text-slate-500 block">Cosine Similarity:</span>
                <span className="font-bold text-slate-800 dark:text-slate-200 text-lg">
                  {Math.round(analysis.jobMatch.semanticSimilarityScore * 100)}%
                </span>
              </div>
              <div>
                <span className="text-slate-500 block">Matched Skills:</span>
                <span className="font-bold text-emerald-600 text-lg">{analysis.jobMatch.matchingSkills.length}</span>
              </div>
              <div>
                <span className="text-slate-500 block">Missing Skills:</span>
                <span className="font-bold text-red-600 text-lg">{analysis.jobMatch.missingSkills.length}</span>
              </div>
            </div>
          </div>
        )}

        {/* Report Footer Notice */}
        <div className="pt-6 border-t border-slate-200 dark:border-slate-800 text-[11px] text-slate-400 flex items-center justify-between flex-wrap gap-2">
          <span>ResumeAI Open-Source ATS Scoring & Semantic NLP Engine</span>
          <span>Timestamp: {new Date().toLocaleDateString()}</span>
        </div>
      </div>
    </div>
  );
}
